### ISSUE TITLE
Move systemd files in this repo

### ISSUE THREAD

**Issue by jdorel** [pastleo/xrandr-watcher#4]
Instead of having the systemd files in the AUR, could they be directly in this repo ?

**Comment by pastleo** [comment]
they are actually in this repo, just different branch: https://github.com/pastleo/xrandr-watcher/blob/master/xrandr-watcher.service

**Comment by jdorel** [comment]
Just made a PR to add this info on the readme : #5 
Is there a particular reason to add the systemd file in a different branch ? For the PKGBUILD I assume it is for AUR upload ?

**Comment by pastleo** [comment]
the master branch is for AUR upload, yes. At the time I might think that systemd file is more like system integration
Anyway, thank you for the PR, I will merge for better documentation
