### ISSUE TITLE
Contradicting messages and docs

### ISSUE THREAD

**Issue by g-voelker** [pastleo/xrandr-watcher#9]
The service is listening to `~/.xrandr-changed` However, the docs and the default script hint to `~/.xrander-watcher`. I had to double check the systemd files to check which file is actually used. There are also contradicting statements in the AUR / Arch Wiki

Documentation and default scripts should be updated to avoid confusing the users.

**Comment by pastleo** [comment]
my bad, let me correct them

**Comment by pastleo** [comment]
docs are updated, thank you for pointing out
